-- L'Étoile du Liban — initial catalog seed
-- Run after schema.sql. Prices are left NULL — fill in real pricing from the admin panel.

insert into products (name, description, price, image_url, category, category_eyebrow, category_description, size, product_tag, ritual_tags, ritual_detail, sort_order) values

-- Classic Heritage Soaps
('Olive Oil Soap', 'Protects skin, supports anti-aging care, and even helps remove tough fabric stains.', null, null, 'Classic Heritage Soaps', 'Daily Cleansing Rituals', 'Traditional Lebanese soapmaking shaped into gentle daily care for face, body, scalp, and home.', '140G', 'Olive Leaf', array['purify','strengthen'], 'Made with cold-pressed olive oil for gentle daily cleansing on skin and fabric alike.', 100),
('Laurel Soap', 'Deep cleansing with antiseptic properties while nourishing skin and caring for the scalp.', null, null, 'Classic Heritage Soaps', 'Daily Cleansing Rituals', 'Traditional Lebanese soapmaking shaped into gentle daily care for face, body, scalp, and home.', '140G', 'Laurel & Olive', array['purify','restore'], 'A traditional Aleppo-style blend of laurel berry oil and olive oil for scalp and skin care.', 101),
('Jasmine Soap', 'Keeps skin soft and moisturized while uplifting the mood with a graceful floral aroma.', null, null, 'Classic Heritage Soaps', 'Daily Cleansing Rituals', 'Traditional Lebanese soapmaking shaped into gentle daily care for face, body, scalp, and home.', '300G', 'Imperial Jasmine', array['nourish','perfume'], 'Infused with jasmine for a soft, floral daily ritual that moisturizes as it cleanses.', 102),
('Green Tea Soap', 'Antioxidant-rich care that softens, soothes, and supports a brighter healthy glow.', null, null, 'Classic Heritage Soaps', 'Daily Cleansing Rituals', 'Traditional Lebanese soapmaking shaped into gentle daily care for face, body, scalp, and home.', '300G', 'Green Tea & Lemongrass', array['restore','nourish'], 'Green tea and lemongrass combine for an antioxidant-rich, brightening daily wash.', 103),
('Lavender Soap', 'A calming soap designed to soothe stress, sunburn, scarring, eczema, and psoriasis-prone skin.', null, null, 'Classic Heritage Soaps', 'Daily Cleansing Rituals', 'Traditional Lebanese soapmaking shaped into gentle daily care for face, body, scalp, and home.', '300G', 'Lavender Fields', array['restore'], 'Calming lavender formulated for sensitive, irritation-prone skin and stress relief.', 104),
('Rosemary Soap', 'Purifies acne-prone skin from impurities and germs with a long-lasting herbal fragrance.', null, null, 'Classic Heritage Soaps', 'Daily Cleansing Rituals', 'Traditional Lebanese soapmaking shaped into gentle daily care for face, body, scalp, and home.', '300G', 'Rosemary Herb', array['purify'], 'An herbal rosemary blend that purifies acne-prone skin with a long-lasting fragrance.', 105),

-- Loofah Exfoliating Soaps
('Chamomile Loofah', 'Removes dead skin, cleans pores, boosts circulation, and leaves a calming sensation.', null, null, 'Loofah Exfoliating Soaps', 'Polish & Renew', 'Natural loofah is embedded into each bar for gentle exfoliation, circulation support, and glowing softness.', '70G', 'Chamomile Calm', array['exfoliate','restore'], 'Natural loofah embedded with chamomile for a gentle, calming exfoliation ritual.', 200),
('Wild Mint Loofah', 'Refreshes skin while helping relieve muscle cramps through a cooling aromatic sensation.', null, null, 'Loofah Exfoliating Soaps', 'Polish & Renew', 'Natural loofah is embedded into each bar for gentle exfoliation, circulation support, and glowing softness.', '70G', 'Wild Mint', array['exfoliate','restore'], 'A cooling wild mint loofah bar that refreshes skin and eases muscle tension.', 201),
('Cedar Loofah', 'Celebrates Lebanon''s aromatic identity while smoothing skin and renewing texture.', null, null, 'Loofah Exfoliating Soaps', 'Polish & Renew', 'Natural loofah is embedded into each bar for gentle exfoliation, circulation support, and glowing softness.', '70G', 'Lebanese Cedar', array['exfoliate','perfume'], 'Cedar-scented loofah soap that smooths and renews skin texture.', 202),
('Lavender Loofah', 'Smooths skin and offers a soothing aromatic experience that helps reduce stress and anxiety.', null, null, 'Loofah Exfoliating Soaps', 'Polish & Renew', 'Natural loofah is embedded into each bar for gentle exfoliation, circulation support, and glowing softness.', '70G', 'Lavender Calm', array['exfoliate','restore'], 'Lavender-infused loofah soap for a soothing, stress-relieving exfoliation ritual.', 203),
('Green Tea Loofah', 'Exfoliates, refreshes, boosts circulation, and supports a tender renewed skin feel.', null, null, 'Loofah Exfoliating Soaps', 'Polish & Renew', 'Natural loofah is embedded into each bar for gentle exfoliation, circulation support, and glowing softness.', '70G', 'Green Tea Freshness', array['exfoliate','restore'], 'Green tea loofah soap that exfoliates while boosting circulation and freshness.', 204),

-- Organic Body Splashes
('Jasmine Body Splash', 'A luxurious floral scent that lasts all day and leaves a smooth organic touch.', null, null, 'Organic Body Splashes', 'Aromatic Signature', 'Light, graceful scent rituals for skin, hair, and clothes with organic oils and botanical notes.', '100ML', 'Imperial Jasmine', array['perfume'], 'A long-lasting jasmine body splash for skin, hair, and clothes.', 300),
('Damascus Rose Body Splash', 'A romantic rose scent crowned with a refreshing smooth finish for body, hair, and clothes.', null, null, 'Organic Body Splashes', 'Aromatic Signature', 'Light, graceful scent rituals for skin, hair, and clothes with organic oils and botanical notes.', '100ML', 'Damascus Rose', array['perfume'], 'A romantic Damascus rose splash with a refreshing, smooth finish.', 301),
('Papaya Body Splash', 'A sweet fruity scent that feels fresh, smooth, and naturally joyful throughout the day.', null, null, 'Organic Body Splashes', 'Aromatic Signature', 'Light, graceful scent rituals for skin, hair, and clothes with organic oils and botanical notes.', '100ML', 'Papaya Fruit', array['perfume'], 'A sweet papaya body splash for a fresh, joyful daily scent ritual.', 302),
('Vanilla Body Splash', 'A warm comforting scent with a soft organic finish for a soothing aromatic experience.', null, null, 'Organic Body Splashes', 'Aromatic Signature', 'Light, graceful scent rituals for skin, hair, and clothes with organic oils and botanical notes.', '100ML', 'Vanilla Cream', array['perfume'], 'A warm, comforting vanilla body splash with a soft organic finish.', 303),

-- Treatment & Beauty Care
('Turmeric Honey Soap', 'Helps unify skin tone, reduce pigmentation and post-acne marks, and restore radiance.', null, null, 'Treatment & Beauty Care', 'Targeted Botanical Care', 'Focused care for tone, texture, hydration, lips, and weekly exfoliation.', '100G', 'Honey & Turmeric', array['restore','nourish'], 'A honey and turmeric soap that helps even tone and restore radiance.', 400),
('Alum Honey Soap', 'Designed for dark areas, pore tightening, sweat reduction, and odor control.', null, null, 'Treatment & Beauty Care', 'Targeted Botanical Care', 'Focused care for tone, texture, hydration, lips, and weekly exfoliation.', '100G', 'Honey Mineral', array['purify','strengthen'], 'A mineral-rich honey and alum soap for pore tightening and odor control.', 401),
('Acne Honey Soap', 'Targets acne bacteria, redness, itchiness, and inflammation without leaving scars.', null, null, 'Treatment & Beauty Care', 'Targeted Botanical Care', 'Focused care for tone, texture, hydration, lips, and weekly exfoliation.', '100G', 'Honey & Pine Tar', array['purify'], 'A honey and pine tar soap formulated to target acne-causing bacteria and inflammation.', 402),
('Shea Butter & Green Tea Scrub', 'Gently exfoliates dead cells, softens imperfections, and leaves skin fresh and moisturized.', null, null, 'Treatment & Beauty Care', 'Targeted Botanical Care', 'Focused care for tone, texture, hydration, lips, and weekly exfoliation.', '150G', 'Sweet Green Tea', array['exfoliate','nourish'], 'A gentle shea butter and green tea scrub for weekly exfoliation and softness.', 403),
('Pure Shea Butter', 'Deeply moisturizes dry areas, supports elasticity, and helps reduce premature lines.', null, null, 'Treatment & Beauty Care', 'Targeted Botanical Care', 'Focused care for tone, texture, hydration, lips, and weekly exfoliation.', '150G', 'Pure Shea', array['nourish'], '100% pure shea butter for deep moisture and skin elasticity.', 404),
('Lip Balm Night Secret', 'Repairs chapped lips, strengthens the moisture barrier, and restores natural color.', null, null, 'Treatment & Beauty Care', 'Targeted Botanical Care', 'Focused care for tone, texture, hydration, lips, and weekly exfoliation.', '30G', 'Fruity Milk Shake', array['nourish'], 'A nourishing fruity milkshake-scented lip balm for chapped, dry lips.', 405),
('Lip Balm Damascus Rose', 'Protects lips from dryness while leaving them soft, healthy, and delicately scented.', null, null, 'Treatment & Beauty Care', 'Targeted Botanical Care', 'Focused care for tone, texture, hydration, lips, and weekly exfoliation.', '30G', 'Damascus Rose', array['nourish','perfume'], 'A Damascus rose-scented lip balm that protects against dryness.', 406),

-- Body Oils
('Body Oil Wild Mint', 'Relieves muscle cramps, joint pain, and headaches while energizing the body after workouts.', null, null, 'Body Oils', 'Perfumed Nourishment', 'Lightweight non-greasy oils that absorb quickly, deeply moisturize, and leave a refined lasting scent.', '40ML / 80ML', 'Wild Mint', array['restore'], 'A wild mint massage oil that energizes and relieves muscle tension after activity.', 500),
('Body Oil Chamomile & Tea Tree', 'A calming massage oil suitable for all skin types and safe for newborns.', null, null, 'Body Oils', 'Perfumed Nourishment', 'Lightweight non-greasy oils that absorb quickly, deeply moisturize, and leave a refined lasting scent.', '40ML / 80ML', 'Chamomile Tea Tree', array['restore'], 'A gentle chamomile and tea tree oil suitable for all ages, including newborns.', 501),
('Body Oil Lavender', 'Supports better sleep, relaxed breathing, and a soothing moisturized skin feel.', null, null, 'Body Oils', 'Perfumed Nourishment', 'Lightweight non-greasy oils that absorb quickly, deeply moisturize, and leave a refined lasting scent.', '40ML / 80ML', 'Lavender', array['restore'], 'A calming lavender body oil that supports restful sleep and relaxation.', 502),
('Body Oil Musk', 'A sophisticated oil perfume and massage oil with a luxurious long-lasting scent.', null, null, 'Body Oils', 'Perfumed Nourishment', 'Lightweight non-greasy oils that absorb quickly, deeply moisturize, and leave a refined lasting scent.', '40ML / 80ML', 'Musk', array['perfume'], 'A sophisticated musk oil that doubles as perfume and massage oil.', 503),
('Body Oil Green Tea & Lemongrass', 'Fresh, soft, and elegant aromatic oil for daily moisturization and irresistible freshness.', null, null, 'Body Oils', 'Perfumed Nourishment', 'Lightweight non-greasy oils that absorb quickly, deeply moisturize, and leave a refined lasting scent.', '40ML / 80ML', 'Green Tea Lemongrass', array['perfume','nourish'], 'A fresh green tea and lemongrass oil for daily aromatic moisturization.', 504),
('Body Oil Tripoli Mist', 'A nostalgic orange blossom trail inspired by the old souks of Tripoli.', null, null, 'Body Oils', 'Perfumed Nourishment', 'Lightweight non-greasy oils that absorb quickly, deeply moisturize, and leave a refined lasting scent.', '40ML / 80ML', 'Orange Blossom', array['perfume'], 'An orange blossom body oil inspired by the souks of Tripoli.', 505),
('Body Oil Lebanese Mist', 'A retro Lebanese aroma with amber, white musk, pine, and ylang ylang elegance.', null, null, 'Body Oils', 'Perfumed Nourishment', 'Lightweight non-greasy oils that absorb quickly, deeply moisturize, and leave a refined lasting scent.', '40ML / 80ML', 'Orange Blossom, Pine & Musk', array['perfume'], 'A retro Lebanese-inspired oil blending amber, musk, pine, and ylang ylang.', 506),

-- Green Tea Hair Collection
('Hair Nourishing Serum', 'Forms a protective layer against sun, dust, and humidity while making hair shinier and manageable.', null, null, 'Green Tea Hair Collection', 'Scalp & Shine', 'Organic green tea hair care designed to soothe the scalp, support healthy growth, and restore shine.', '100ML', 'Green Tea Shine', array['strengthen','nourish'], 'A green tea hair serum that protects, strengthens, and adds lasting shine.', 600);
